name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: ["index.html"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar código
        uses: actions/configure-pages@v4

      - name: Fazer upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
